### ISSUE TITLE
Can't get demo to work / How can I test in es5?

### ISSUE THREAD

**Issue by remiX-** [avgjs/pixi-richtext#3]
Hey,

I've been trying to get this working in just a plain index.html page with javascript but my webpack to compile is not working.

Nor can I test the demo as it fails on es6 import.

The usage in the readme doesn't help much

**Comment by Icemic** [comment]
While there's no es5 version supplied, you can pull the repo to your local disk, then edit `.babelrc` to fit es5, and run `npm prepublish`. And find file in `/dist`

**Comment by remiX-** [comment]
What do I change it to fit es5?

I'm unable to `npm nstall` directly after pulling without making any changes
![image](https://user-images.githubusercontent.com/2831747/38409494-f1a1451e-3981-11e8-897c-74b319da39cc.png)

**Comment by Icemic** [comment]
sorry, but you need a *nix environment, such as git-bash or cygwin.
Or, modify `prepublish` script in `package.json` to `set BABEL_ENV=production && webpack` instead of `BABEL_ENV=production webpack` to avoid the issue. (I'm not sure, it's probably like this)

However, I'm planning to use rollup in replace of webpack, so that both es6 and es5 version can be supplied easily. It may need some time.

**Comment by remiX-** [comment]
That was using gitbash -- I'll try that though on Monday

**Comment by remiX-** [comment]
How do I modify the prepublish script in the package.json?

EDIT:
Nevermind, got it - cannot find a way to build non-minified version, tried everything I found online but always but minified :/
