### ISSUE TITLE
returnu is not defined

### ISSUE THREAD

**Issue by king514jy** [avgjs/pixi-richtext#4]
![image](https://user-images.githubusercontent.com/5669543/50630863-4eddd400-0f7d-11e9-840b-2a42095d9c6b.png)
![image](https://user-images.githubusercontent.com/5669543/50630875-5e5d1d00-0f7d-11e9-9743-93b94545c455.png)

**Comment by Icemic** [comment]
Cannot reproduce it. What about making a demo on codepen?

**Comment by Icemic** [comment]
Closed because there's no update for days

**Comment by jdelrue** [comment]
Got the same error!

https://jsfiddle.net/ugvbdL57/

**Comment by Icemic** [comment]
> Got the same error!
> 
> https://jsfiddle.net/ugvbdL57/

your example seems broken?
![image](https://user-images.githubusercontent.com/837432/55341262-e7caaf80-54d8-11e9-9d29-2005d61e0e7c.png)

**Comment by jdelrue** [comment]
Sorry, tried to debug in your code (I thought it might be a typo). Please retry!

**Comment by madtisa** [comment]
The problem is still exist (v1.1.2). 
Workaround is to change `returnu` to `return u` in files `pixi.richtext.es5.js` and `pixi.richtext.umd.js`
It's most probably caused by minification (most likely `babel-preset-minify` package). I tried to update them, since I didn't work with rollup I ran out of patience before I was able to resolve all conflicts.

@Icemic, please reopen this issue
